/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { OcearaMRVRegistry } from './OcearaMRVRegistry.js';
export * as factories from './factories/index.js';
export { OcearaMRVRegistry__factory } from './factories/OcearaMRVRegistry__factory.js';