/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface OcearaMRVRegistryInterface extends Interface {
    getFunction(nameOrSignature: "admin" | "getMRV" | "getProject" | "registerProject" | "rejectProject" | "setVerifier" | "submitMRV" | "verifiers" | "verifyProject"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "MRVSubmitted" | "ProjectRegistered" | "ProjectRejected" | "ProjectVerified" | "VerifierUpdated"): EventFragment;

    encodeFunctionData(functionFragment: 'admin', values?: undefined): string;
encodeFunctionData(functionFragment: 'getMRV', values: [string]): string;
encodeFunctionData(functionFragment: 'getProject', values: [string]): string;
encodeFunctionData(functionFragment: 'registerProject', values: [string, string]): string;
encodeFunctionData(functionFragment: 'rejectProject', values: [string]): string;
encodeFunctionData(functionFragment: 'setVerifier', values: [AddressLike, boolean]): string;
encodeFunctionData(functionFragment: 'submitMRV', values: [string, string, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'verifiers', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'verifyProject', values: [string]): string;

    decodeFunctionResult(functionFragment: 'admin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getMRV', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getProject', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'registerProject', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'rejectProject', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setVerifier', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'submitMRV', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'verifiers', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'verifyProject', data: BytesLike): Result;
  }

  
    export namespace MRVSubmittedEvent {
      export type InputTuple = [projectId: string, mrvHash: string, biomass: BigNumberish, carbonEstimate: BigNumberish];
      export type OutputTuple = [projectId: string, mrvHash: string, biomass: bigint, carbonEstimate: bigint];
      export interface OutputObject {projectId: string, mrvHash: string, biomass: bigint, carbonEstimate: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ProjectRegisteredEvent {
      export type InputTuple = [projectId: string, owner: AddressLike, locationHash: string];
      export type OutputTuple = [projectId: string, owner: string, locationHash: string];
      export interface OutputObject {projectId: string, owner: string, locationHash: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ProjectRejectedEvent {
      export type InputTuple = [projectId: string, verifier: AddressLike];
      export type OutputTuple = [projectId: string, verifier: string];
      export interface OutputObject {projectId: string, verifier: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ProjectVerifiedEvent {
      export type InputTuple = [projectId: string, verifier: AddressLike];
      export type OutputTuple = [projectId: string, verifier: string];
      export interface OutputObject {projectId: string, verifier: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace VerifierUpdatedEvent {
      export type InputTuple = [verifier: AddressLike, authorized: boolean];
      export type OutputTuple = [verifier: string, authorized: boolean];
      export interface OutputObject {verifier: string, authorized: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface OcearaMRVRegistry extends BaseContract {
    
    connect(runner?: ContractRunner | null): OcearaMRVRegistry;
    waitForDeployment(): Promise<this>;

    interface: OcearaMRVRegistryInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    admin: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    getMRV: TypedContractMethod<
      [projectId: string, ],
      [[string, bigint, bigint, string, bigint]],
      'view'
    >
    

    
    getProject: TypedContractMethod<
      [projectId: string, ],
      [[string, string, string, bigint, bigint]],
      'view'
    >
    

    
    registerProject: TypedContractMethod<
      [projectId: string, locationHash: string, ],
      [void],
      'nonpayable'
    >
    

    
    rejectProject: TypedContractMethod<
      [projectId: string, ],
      [void],
      'nonpayable'
    >
    

    
    setVerifier: TypedContractMethod<
      [verifier: AddressLike, authorized: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    submitMRV: TypedContractMethod<
      [projectId: string, mrvHash: string, biomass: BigNumberish, carbonEstimate: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    verifiers: TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    verifyProject: TypedContractMethod<
      [projectId: string, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'admin'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getMRV'): TypedContractMethod<
      [projectId: string, ],
      [[string, bigint, bigint, string, bigint]],
      'view'
    >;
getFunction(nameOrSignature: 'getProject'): TypedContractMethod<
      [projectId: string, ],
      [[string, string, string, bigint, bigint]],
      'view'
    >;
getFunction(nameOrSignature: 'registerProject'): TypedContractMethod<
      [projectId: string, locationHash: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'rejectProject'): TypedContractMethod<
      [projectId: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setVerifier'): TypedContractMethod<
      [verifier: AddressLike, authorized: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'submitMRV'): TypedContractMethod<
      [projectId: string, mrvHash: string, biomass: BigNumberish, carbonEstimate: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'verifiers'): TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'verifyProject'): TypedContractMethod<
      [projectId: string, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'MRVSubmitted'): TypedContractEvent<MRVSubmittedEvent.InputTuple, MRVSubmittedEvent.OutputTuple, MRVSubmittedEvent.OutputObject>;
getEvent(key: 'ProjectRegistered'): TypedContractEvent<ProjectRegisteredEvent.InputTuple, ProjectRegisteredEvent.OutputTuple, ProjectRegisteredEvent.OutputObject>;
getEvent(key: 'ProjectRejected'): TypedContractEvent<ProjectRejectedEvent.InputTuple, ProjectRejectedEvent.OutputTuple, ProjectRejectedEvent.OutputObject>;
getEvent(key: 'ProjectVerified'): TypedContractEvent<ProjectVerifiedEvent.InputTuple, ProjectVerifiedEvent.OutputTuple, ProjectVerifiedEvent.OutputObject>;
getEvent(key: 'VerifierUpdated'): TypedContractEvent<VerifierUpdatedEvent.InputTuple, VerifierUpdatedEvent.OutputTuple, VerifierUpdatedEvent.OutputObject>;

    filters: {
      
      'MRVSubmitted(string,string,uint256,uint256)': TypedContractEvent<MRVSubmittedEvent.InputTuple, MRVSubmittedEvent.OutputTuple, MRVSubmittedEvent.OutputObject>;
      MRVSubmitted: TypedContractEvent<MRVSubmittedEvent.InputTuple, MRVSubmittedEvent.OutputTuple, MRVSubmittedEvent.OutputObject>;
    

      'ProjectRegistered(string,address,string)': TypedContractEvent<ProjectRegisteredEvent.InputTuple, ProjectRegisteredEvent.OutputTuple, ProjectRegisteredEvent.OutputObject>;
      ProjectRegistered: TypedContractEvent<ProjectRegisteredEvent.InputTuple, ProjectRegisteredEvent.OutputTuple, ProjectRegisteredEvent.OutputObject>;
    

      'ProjectRejected(string,address)': TypedContractEvent<ProjectRejectedEvent.InputTuple, ProjectRejectedEvent.OutputTuple, ProjectRejectedEvent.OutputObject>;
      ProjectRejected: TypedContractEvent<ProjectRejectedEvent.InputTuple, ProjectRejectedEvent.OutputTuple, ProjectRejectedEvent.OutputObject>;
    

      'ProjectVerified(string,address)': TypedContractEvent<ProjectVerifiedEvent.InputTuple, ProjectVerifiedEvent.OutputTuple, ProjectVerifiedEvent.OutputObject>;
      ProjectVerified: TypedContractEvent<ProjectVerifiedEvent.InputTuple, ProjectVerifiedEvent.OutputTuple, ProjectVerifiedEvent.OutputObject>;
    

      'VerifierUpdated(address,bool)': TypedContractEvent<VerifierUpdatedEvent.InputTuple, VerifierUpdatedEvent.OutputTuple, VerifierUpdatedEvent.OutputObject>;
      VerifierUpdated: TypedContractEvent<VerifierUpdatedEvent.InputTuple, VerifierUpdatedEvent.OutputTuple, VerifierUpdatedEvent.OutputObject>;
    
    };
  }