'use client'

import Link from 'next/link'
import { motion } from 'framer-motion'
import PlatformNav from '@/components/PlatformNav'

export default function ReportsPage() {
  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-900 via-blue-900 to-slate-900">
      <header className="border-b border-white/20 py-4 px-4">
        <div className="flex items-center justify-between max-w-6xl mx-auto">
          <Link href="/" className="text-xl font-bold text-white/90 hover:text-white">
            🌊 Oceara
          </Link>
          <PlatformNav />
        </div>
      </header>

      <main className="max-w-3xl mx-auto px-4 py-12">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          className="bg-white/10 backdrop-blur-lg rounded-2xl p-8 border border-white/20"
        >
          <h1 className="text-2xl sm:text-3xl font-bold text-white mb-2">Reports</h1>
          <p className="text-gray-300 mb-6">
            Carbon Estimation Reports (Pre-Certification) and MRV reports are generated by MRV administrators for verified projects.
          </p>
          <div className="space-y-4">
            <Link
              href="/admin"
              className="block w-full py-3 px-4 bg-gradient-to-r from-blue-500 to-emerald-500 rounded-lg text-white font-semibold text-center hover:shadow-lg transition-all"
            >
              Go to MRV Administrator dashboard
            </Link>
            <Link
              href="/buyer"
              className="block w-full py-3 px-4 bg-white/10 border border-white/20 rounded-lg text-white font-semibold text-center hover:bg-white/20 transition-all"
            >
              View Project Registry
            </Link>
          </div>
          <p className="text-gray-400 text-sm mt-6">
            If you are an administrator, sign in to generate and download reports. Institutions can request reports via the Project Registry.
          </p>
        </motion.div>

        <div className="text-center mt-8">
          <Link href="/" className="text-gray-400 hover:text-white text-sm">
            ← Back to Home
          </Link>
        </div>
      </main>
    </div>
  )
}
